import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./StoreProvider";
import { Header } from "../components/Header";
import MyApp from "./MyApp";
// import { useTranslation } from 'react-i18next'
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const { Event_reducer } = useSelector((st) => st)
  // const { t } = useTranslation()

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <MyApp children={children} />
        </body>
      </Providers>
    </html>
  );
}
