import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./StoreProvider";
import MyApp from "./MyApp.jsx";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: {
//     default: "My Title",
//     template: '%s | My Title',
//   },
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MyApp>
            {children}
          </MyApp>
        </Providers>
      </body>
    </html>
  );
}
