import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./StoreProvider";
import MyApp from "./MyApp";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: {
//     default: "My Title",
//     template: '%s | My Title',
//   },
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <MyApp children={children} />
        </body>
      </Providers>
    </html>
  );
}
